GET http://localhost:3001/api/persons

###

GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/1

###
GET http://localhost:3001/api/persons/8

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "New Name",
    "number": "123-456"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

###
DELETE http://localhost:3001/api/persons/1

###
DELETE http://localhost:3001/api/persons/8